version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/dolph/docker/postgres/data:/var/lib/postgresql/data
      - /home/dolph/docker/postgres/entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - db_network


  adminer:
    image: adminer
    restart: always
    ports:
      - 38080:8080
    networks:
      - db_network
      - web_network
    depends_on:
      - db


  happy-quokka:
    container_name: happy-quokka
    restart: always
    build: .
    networks:
      - db_network
      - web_network
#    volumes:
#      - ../env.docker:/.env


  nginx:
    container_name: nginx
    restart: always
    image: "nginx:latest"
    ports:
      - "80:80"
    volumes:
      - ./nginx/happyquokka.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web_network
    depends_on:
      - happy-quokka

networks:
  db_network:
#    external: true
  web_network:
#    external: true