version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/dolph/docker/postgres/data:/var/lib/postgresql/data
      - /home/dolph/docker/postgres/entrypoint:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - db_network


  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 38080:8080
    networks:
      - db_network
      - web_network
    depends_on:
      - db


networks:
  db_network:
#    external: true
  web_network:
#    external: true