# -*- encoding: utf-8 -*-
from sqlalchemy import func
from apps import db


class Episodes(db.Model):
    __tablename__ = 'POD_Episodes'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_uuid = db.Column(db.String(36), nullable=False)
    uuid = db.Column(db.String(36), nullable=False)

    addict_id = db.Column(db.Integer, default=0)
    name = db.Column(db.Text, nullable=False)
    addict_podcast_id = db.Column(db.Integer, nullable=False)
    guid = db.Column(db.Text, nullable=False)
    url = db.Column(db.Text)
    publication_date = db.Column(db.BigInteger, nullable=False)
    creator = db.Column(db.Text)
    short_description = db.Column(db.Text)
    content = db.Column(db.Text)
    # comment_rss = db.Column(db.Text)
    download_url = db.Column(db.Text)
    duration = db.Column(db.Integer, nullable=False, default=-1)       # taken from duration_ms
    # duration_ms = db.Column(db.Integer, nullable=False, default=-1)
    # size = db.Column(db.Integer, nullable=False)
    # rating = db.Column(db.REAL, nullable=False, default=-1)
    # downloaded_status = db.Column(db.TEXT, nullable=False, default='-1')
    favorite = db.Column(db.Integer, nullable=False)
    seen_status = db.Column(db.Integer, nullable=False)
    # downloaded_date = db.Column(db.Integer)
    new_status = db.Column(db.Integer, nullable=False)
    # playing_status = db.Column(db.Integer, nullable=False, default=0)
    position_to_resume = db.Column(db.Integer)
    deleted_status = db.Column(db.Integer, nullable=False)
    local_file_name = db.Column(db.Text)
    thumbnail_id = db.Column(db.Integer)
    # comments_last_modified = db.Column(db.Integer, nullable=False)
    # comments_etag = db.Column(db.Text, nullable=False)
    # flattr = db.Column(db.Text, default='')
    # is_virtual = db.Column(db.Integer, default=0)
    is_artwork_extracted = db.Column(db.Integer, default=0)
    # virtualPodcastName = db.Column(db.Text, default='')
    # normalizedType = db.Column(db.Integer, default=0)
    # hasBeenFlattred = db.Column(db.Integer, default=0)
    playback_date = db.Column(db.BigInteger, nullable=False, default=-1)
    # download_error_msg = db.Column(db.Text)
    # media_extracted_artwork_id = db.Column(db.Integer, default=-1)
    chapters_extracted = db.Column(db.Integer, default=0)
    # server_id = db.Column(db.Integer, default=-1)
    # automatically_shared = db.Column(db.Integer, default=0)
    # downloaded_status_int = db.Column(db.Integer, nullable=False, default=0)
    # donation_url = db.Column(db.Text)
    # explicit = db.Column(db.Integer, default=0)
    # iTunesType = db.Column(db.Integer, default=0)
    # seasonNb = db.Column(db.Integer, default=-1)
    # episodeNb = db.Column(db.Integer, default=-1)
    transcript_url = db.Column(db.Text)
    # chapters_url = db.Column(db.Text)
    # seasonName = db.Column(db.Text)
    # thumbsRating = db.Column(db.Integer, nullable=False, default=0)
    # alternate_urls = db.Column(db.Text, default=None)


class Chapters(db.Model):
    __tablename__ = 'POD_Chapters'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_uuid = db.Column(db.String(36), nullable=False)
    uuid = db.Column(db.String(36), nullable=False)

    addict_id = db.Column(db.Integer, default=0)
    addict_podcast_id = db.Column(db.Integer, nullable=False)
    addict_episode_id = db.Column(db.Integer, nullable=False)
    start = db.Column(db.Integer, nullable=False)
    name = db.Column(db.Text)
    description = db.Column(db.Text)
    url = db.Column(db.Text)
    # artworkId = db.Column(db.Integer)
    custom_bookmark = db.Column(db.Integer, default=0)
    # diaporamaFlag = db.Column(db.Integer, default=0)
    update_date = db.Column(db.BigInteger, default=0)
    isMuted = db.Column(db.Integer, default=0)
    # isMusic = db.Column(db.Integer, default=0)
    # loopMode = db.Column(db.Integer, default=0)


class Podcasts(db.Model):
    __tablename__ = 'POD_Podcasts'

    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    user_uuid = db.Column(db.String(36), nullable=False)
    uuid = db.Column(db.String(36), nullable=False)

    addict_id = db.Column(db.Integer, default=0)
    name = db.Column(db.Text, nullable=False)
    # team_id = db.Column(db.Integer, nullable=False)
    # category = db.Column(db.Text)
    # type = db.Column(db.Text, nullable=False)
    subscribed_status = db.Column(db.Integer, nullable=False)
    # version = db.Column(db.Integer, nullable=False)
    homepage = db.Column(db.Text)
    latest_publication_date = db.Column(db.BigInteger, nullable=True)
    feed_url = db.Column(db.Text, unique=True, nullable=False)
    # favorite = db.Column(db.Integer)
    # rating = db.Column(db.REAL, nullable=False)
    # update_status = db.Column(db.Integer, nullable=False)
    # update_date = db.Column(db.Integer)
    # thumbnail_id = db.Column(db.Integer)
    # store_url = db.Column(db.Text)
    # last_modified = db.Column(db.BigInteger, nullable=False)
    # etag = db.Column(db.Text, nullable=False)
    # initialized_status = db.Column(db.Integer, nullable=False, default=0)
    # CHARSET = db.Column(db.Text, default='')
    # last_update_failure = db.Column(db.Integer, nullable=False, default=0)
    # flattr = db.Column(db.Text, default='')
    # is_virtual = db.Column(db.Integer, default=0)
    # is_complete = db.Column(db.Integer, default=1)
    # language = db.Column(db.Text)
    author = db.Column(db.Text)
    description = db.Column(db.Text)
    # custom_name = db.Column(db.Text)
    # priority = db.Column(db.Integer, nullable=False, default=1)
    # accept_audio = db.Column(db.Integer, nullable=False, default=1)
    # accept_video = db.Column(db.Integer, nullable=False, default=1)
    # accept_text = db.Column(db.Integer, nullable=False, default=1)
    # filter_included_keywords = db.Column(db.Text)
    # filter_excluded_keywords = db.Column(db.Text)
    # update_error_message = db.Column(db.Text)
    # authentication = db.Column(db.Integer, default=0)
    # login = db.Column(db.Text, default='')
    # password = db.Column(db.Text, default='')
    # automaticRefresh = db.Column(db.Integer, default=1)
    folder_name = db.Column(db.Text, default='')
    # private = db.Column(db.Integer, default=0)
    # iTunesID = db.Column(db.Text, default='')
    # subscribers = db.Column(db.Integer, default=-1)
    # averageDuration = db.Column(db.Integer, default=-1)
    # frequency = db.Column(db.Integer, default=-1)
    # episodesNb = db.Column(db.Integer, default=-1)
    # explicit = db.Column(db.Integer, default=0)
    # iTunesType = db.Column(db.Integer, default=0)
    # reviews = db.Column(db.Integer, default=0)
    # position = db.Column(db.Integer, default=0)
    # server_id = db.Column(db.Integer, default=-1)
    muted = db.Column(db.Integer, default=0)
    # hub_url = db.Column(db.Text)
    topic_url = db.Column(db.Text)
    # websubSubscribed = db.Column(db.Integer, default=0)
    # filter_chapter_excluded_keywords = db.Column(db.Text, default=None)
    # last_played_episode_date = db.Column(db.Integer, default=-1)
    # guid = db.Column(db.Text, default=None)
    # liveStreamId = db.Column(db.Integer, nullable=False, default=-1)
    # liveStreamStart = db.Column(db.Integer, nullable=False, default=-1)
    # liveStreamEnd = db.Column(db.Integer, nullable=False, default=-1)
    # liveStreamGuid = db.Column(db.Text, default=None)
    # liveStreamStatus = db.Column(db.Integer, nullable=False, default=2)

