"""empty message

Revision ID: 08024916a992
Revises: 8b110f21578c
Create Date: 2024-02-22 10:35:48.239923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08024916a992'
down_revision = '8b110f21578c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ApiExchange',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('module', sa.String(length=20), nullable=False),
    sa.Column('command', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_module', sa.String(length=24), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('group', sa.String(length=36), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Tag')
    op.drop_table('Logs')
    op.drop_table('ApiExchange')
    # ### end Alembic commands ###
