"""empty message

Revision ID: 0d64a4ad4cf3
Revises: e92343605a61
Create Date: 2024-01-02 13:38:20.370751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d64a4ad4cf3'
down_revision = 'e92343605a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_TagVideo', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('YT_TagVideo', 'status')
    # ### end Alembic commands ###
