"""empty message

Revision ID: 120e490e6b37
Revises: c582298249bc
Create Date: 2024-05-23 11:31:26.472897

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '120e490e6b37'
down_revision = 'c582298249bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('YT_Video', schema=None) as batch_op:
        batch_op.drop_column('last_file_check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('YT_Video', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_file_check', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
