"""empty message

Revision ID: 13451c4161ca
Revises: 120e490e6b37
Create Date: 2024-05-24 10:05:33.112525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13451c4161ca'
down_revision = '120e490e6b37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SHTF_Activity',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('basic_pts_ratio', sa.Float(), nullable=False),
    sa.Column('added_pts_ratio', sa.Float(), nullable=True),
    sa.Column('basic_health_ratio', sa.Float(), nullable=False),
    sa.Column('added_health_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SHTF_BodyWeight',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SHTF_Physical',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('activity', sa.Integer(), nullable=False),
    sa.Column('calculated_pts', sa.Integer(), nullable=False),
    sa.Column('calculated_health', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('SHTF_Resources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('owned', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('added_pts_ratio', sa.Float(), nullable=True),
    sa.Column('added_health_ratio', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SHTF_Resources')
    op.drop_table('SHTF_Physical')
    op.drop_table('SHTF_BodyWeight')
    op.drop_table('SHTF_Activity')
    # ### end Alembic commands ###
