"""empty message

Revision ID: 1763923c271e
Revises: 94d3f5fa9c8e
Create Date: 2023-11-30 11:37:29.029998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1763923c271e'
down_revision = '94d3f5fa9c8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_Video', sa.Column('last_visited', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('YT_Video', 'last_visited')
    # ### end Alembic commands ###
