"""empty message

Revision ID: 1ed072c26da9
Revises: c34201b3bf3d
Create Date: 2024-04-01 13:43:14.353859

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ed072c26da9'
down_revision = 'c34201b3bf3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TD_Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('due_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('date_due')
        batch_op.drop_column('time_due')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TD_Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_due', postgresql.TIME(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_due', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_column('due_date')
        batch_op.drop_column('start_date')

    # ### end Alembic commands ###
