"""empty message

Revision ID: 20d1133fe65e
Revises: 
Create Date: 2023-11-16 14:36:24.324460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20d1133fe65e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('password', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('YT_CreatorPlaylist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('creator_name', sa.String(length=48), nullable=False),
    sa.Column('playlist_name', sa.String(length=48), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('YT_Playlist',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=48), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('YT_Tag',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('YT_Video',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=10000), nullable=True),
    sa.Column('channel', sa.String(length=100), nullable=True),
    sa.Column('channel_url', sa.String(length=256), nullable=True),
    sa.Column('thumbnail', sa.LargeBinary(length=4294967295), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('watched', sa.Boolean(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('to_download', sa.Boolean(), nullable=True),
    sa.Column('release_date', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.Column('rate', sa.Integer(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['playlist_id'], ['YT_Playlist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('YT_Chapter',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('end', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['movie_id'], ['YT_Video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('YT_TagVideo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['YT_Tag.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['YT_Video.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('YT_TagVideo')
    op.drop_table('YT_Chapter')
    op.drop_table('YT_Video')
    op.drop_table('YT_Tag')
    op.drop_table('YT_Playlist')
    op.drop_table('YT_CreatorPlaylist')
    op.drop_table('Users')
    # ### end Alembic commands ###
