"""empty message

Revision ID: 28594a56d305
Revises: 3ad9d0425475
Create Date: 2024-03-04 12:41:17.287839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '28594a56d305'
down_revision = '3ad9d0425475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('YT_VideoToProcess',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('youtube_id', sa.String(length=12), nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('YT_Tag')
    op.drop_table('YT_Logs')
    op.add_column('TD_Project', sa.Column('color', sa.String(length=6), nullable=True))
    op.add_column('TD_Project', sa.Column('icon', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('TD_Project', 'icon')
    op.drop_column('TD_Project', 'color')
    op.create_table('YT_Logs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YT_Logs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('from_module', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('user_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='YT_Logs_pkey')
    )
    op.create_table('YT_Tag',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YT_Tag_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('user_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('group', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='YT_Tag_pkey')
    )
    op.drop_table('YT_VideoToProcess')
    # ### end Alembic commands ###
