"""empty message

Revision ID: 3ad9d0425475
Revises: bbcfb48cb3a2
Create Date: 2024-02-22 11:32:10.755654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3ad9d0425475'
down_revision = 'bbcfb48cb3a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TD_Task', sa.Column('date_due', sa.Date(), nullable=True))
    op.add_column('TD_Task', sa.Column('time_due', sa.Time(), nullable=True))
    op.add_column('TD_Task', sa.Column('tags', sa.Text(), nullable=True))
    op.add_column('TD_Task', sa.Column('contexts', sa.Text(), nullable=True))
    op.drop_column('TD_Task', 'time_start')
    op.drop_column('TD_Task', 'date_end')
    op.drop_column('TD_Task', 'date_start')
    op.drop_column('TD_Task', 'time_end')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('TD_Task', sa.Column('time_end', postgresql.TIME(), autoincrement=False, nullable=True))
    op.add_column('TD_Task', sa.Column('date_start', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('TD_Task', sa.Column('date_end', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('TD_Task', sa.Column('time_start', postgresql.TIME(), autoincrement=False, nullable=True))
    op.drop_column('TD_Task', 'contexts')
    op.drop_column('TD_Task', 'tags')
    op.drop_column('TD_Task', 'time_due')
    op.drop_column('TD_Task', 'date_due')
    # ### end Alembic commands ###
