"""empty message

Revision ID: 3d28c43e50a6
Revises: ffbd46b84bc0
Create Date: 2024-02-22 09:54:51.005987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d28c43e50a6'
down_revision = 'ffbd46b84bc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TD_task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('date_start', sa.Date(), nullable=True),
    sa.Column('date_end', sa.Date(), nullable=True),
    sa.Column('time_start', sa.Time(), nullable=True),
    sa.Column('time_end', sa.Time(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.SmallInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('project', sa.String(length=36), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('TD_todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TD_todo',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"TD_todo_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('date_start', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('date_end', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('time_start', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('time_end', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('difficulty', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.SMALLINT(), autoincrement=False, nullable=True),
    sa.Column('project', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='TD_todo_pkey')
    )
    op.drop_table('TD_task')
    # ### end Alembic commands ###
