"""empty message

Revision ID: 4d3a428b2d23
Revises: dd3feb35b8cb
Create Date: 2024-04-01 10:39:51.971277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d3a428b2d23'
down_revision = 'dd3feb35b8cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TD_Task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tick_id', sa.String(length=26), nullable=True))
        batch_op.add_column(sa.Column('tick_project_id', sa.String(length=26), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TD_Task', schema=None) as batch_op:
        batch_op.drop_column('tick_project_id')
        batch_op.drop_column('tick_id')

    # ### end Alembic commands ###
