"""empty message

Revision ID: 58e01d205c72
Revises: a94890bd61ce
Create Date: 2024-01-02 12:11:01.172595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e01d205c72'
down_revision = 'a94890bd61ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_TagVideo', sa.Column('user_uuid', sa.String(length=36), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('YT_TagVideo', 'user_uuid')
    # ### end Alembic commands ###
