"""empty message

Revision ID: 67540079d4af
Revises: 0d64a4ad4cf3
Create Date: 2024-01-02 20:10:25.203821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67540079d4af'
down_revision = '0d64a4ad4cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_Tag', sa.Column('group', sa.String(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('YT_Tag', 'group')
    # ### end Alembic commands ###
