"""empty message

Revision ID: 7181e693cea0
Revises: 1763923c271e
Create Date: 2023-12-21 11:13:57.365044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7181e693cea0'
down_revision = '1763923c271e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('YT_new_modified',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('obiekt', sa.String(length=20), nullable=False),
    sa.Column('obiekt_id', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('YT_new_modified')
    # ### end Alembic commands ###
