"""empty message

Revision ID: 761fa883198c
Revises: af4bcb35fdf9
Create Date: 2024-01-09 13:27:02.565696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '761fa883198c'
down_revision = 'af4bcb35fdf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_Video', sa.Column('chapters', sa.Text(), nullable=True))
    op.alter_column('YT_Video', 'description',
               existing_type=sa.VARCHAR(length=15000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('YT_Video', 'comment',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('YT_Video', 'comment',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
    op.alter_column('YT_Video', 'description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=15000),
               existing_nullable=True)
    op.drop_column('YT_Video', 'chapters')
    # ### end Alembic commands ###
