"""empty message

Revision ID: 84073b56d038
Revises: b82403c9a765
Create Date: 2023-11-20 17:24:15.679133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84073b56d038'
down_revision = 'b82403c9a765'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_Video', sa.Column('video_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('YT_Video', 'video_position')
    # ### end Alembic commands ###
