"""empty message

Revision ID: 89475a9add3b
Revises: 8afc1e16658e
Create Date: 2023-11-22 13:40:58.765125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89475a9add3b'
down_revision = '8afc1e16658e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('YT_Logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('from_module', sa.String(length=24), nullable=False),
    sa.Column('text', sa.String(length=2048), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('YT_Logs')
    # ### end Alembic commands ###
