"""empty message

Revision ID: 8b110f21578c
Revises: 3d28c43e50a6
Create Date: 2024-02-22 10:31:31.679959

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8b110f21578c'
down_revision = '3d28c43e50a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ApiExchange')
    op.drop_table('YT_Logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('YT_Logs',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YT_Logs_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('from_module', sa.VARCHAR(length=24), autoincrement=False, nullable=False),
    sa.Column('text', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('user_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='YT_Logs_pkey')
    )
    op.create_table('ApiExchange',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"ApiExchange_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('command', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('module', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='ApiExchange_pkey')
    )
    # ### end Alembic commands ###
