"""empty message

Revision ID: 94ccec8a47b0
Revises: 39f770e4b26a
Create Date: 2024-04-15 11:32:42.586372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94ccec8a47b0'
down_revision = '39f770e4b26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('POD_Chapters', schema=None) as batch_op:
        batch_op.alter_column('updateDate',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)

    with op.batch_alter_table('POD_Podcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_name', sa.Text(), nullable=True))
        batch_op.alter_column('last_modified',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.drop_column('folderName')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('POD_Podcasts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folderName', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.alter_column('last_modified',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('folder_name')

    with op.batch_alter_table('POD_Chapters', schema=None) as batch_op:
        batch_op.alter_column('updateDate',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
