"""empty message

Revision ID: 94d3f5fa9c8e
Revises: b591d84721a0
Create Date: 2023-11-30 11:07:37.046602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94d3f5fa9c8e'
down_revision = 'b591d84721a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('UserConfig',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('config', sa.String(length=4096), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('UserConfig')
    # ### end Alembic commands ###
