"""empty message

Revision ID: a94890bd61ce
Revises: 7181e693cea0
Create Date: 2023-12-21 11:44:35.192187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a94890bd61ce'
down_revision = '7181e693cea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_new_modified', sa.Column('obiekt_uuid', sa.String(length=36), nullable=False))
    op.drop_column('YT_new_modified', 'obiekt_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_new_modified', sa.Column('obiekt_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('YT_new_modified', 'obiekt_uuid')
    # ### end Alembic commands ###
