"""empty message

Revision ID: af4bcb35fdf9
Revises: 485489777ba2
Create Date: 2024-01-07 18:43:46.452633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af4bcb35fdf9'
down_revision = '485489777ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Users', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Users', 'created')
    # ### end Alembic commands ###
