"""empty message

Revision ID: b591d84721a0
Revises: d20cecd1ffe9
Create Date: 2023-11-28 20:15:50.205137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b591d84721a0'
down_revision = 'd20cecd1ffe9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ApiExchange', sa.Column('module', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ApiExchange', 'module')
    # ### end Alembic commands ###
