"""empty message

Revision ID: b82403c9a765
Revises: 
Create Date: 2023-11-20 11:35:44.798727

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b82403c9a765'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_Video', sa.Column('youtube_id', sa.String(length=12), nullable=False))
    op.drop_column('YT_Video', 'thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_Video', sa.Column('thumbnail', postgresql.BYTEA(), autoincrement=False, nullable=True))
    op.drop_column('YT_Video', 'youtube_id')
    # ### end Alembic commands ###
