"""empty message

Revision ID: b9857fd2a5a1
Revises: 13451c4161ca
Create Date: 2024-05-24 11:04:11.087959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9857fd2a5a1'
down_revision = '13451c4161ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SHTF_Physical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity_uuid', sa.String(length=32), nullable=False))
        batch_op.drop_column('activity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SHTF_Physical', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activity', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('activity_uuid')

    # ### end Alembic commands ###
