"""empty message

Revision ID: c582298249bc
Revises: 033064702c77
Create Date: 2024-05-23 09:56:43.866284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c582298249bc'
down_revision = '033064702c77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('YT_Video', schema=None) as batch_op:
        batch_op.alter_column('file_exist',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('YT_Video', schema=None) as batch_op:
        batch_op.alter_column('file_exist',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
