"""empty message

Revision ID: e92343605a61
Revises: 58e01d205c72
Create Date: 2024-01-02 13:37:20.615452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e92343605a61'
down_revision = '58e01d205c72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('YT_Chapter', 'created')
    op.drop_column('YT_CreatorPlaylist', 'created')
    op.drop_column('YT_Logs', 'created')
    op.drop_column('YT_Playlist', 'created')
    op.drop_column('YT_Tag', 'created')
    op.drop_column('YT_TagVideo', 'created')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_TagVideo', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('YT_Tag', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('YT_Playlist', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('YT_Logs', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('YT_CreatorPlaylist', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('YT_Chapter', sa.Column('created', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
