"""empty message

Revision ID: eb61cddfd674
Revises: f966935b2413
Create Date: 2024-02-16 10:20:50.739991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb61cddfd674'
down_revision = 'f966935b2413'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('YT_Video', 'playlist_uuid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('YT_Video', sa.Column('playlist_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
