"""empty message

Revision ID: f216737215fc
Revises: 94a2c2179949
Create Date: 2024-01-22 19:17:55.143996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f216737215fc'
down_revision = '94a2c2179949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('YT_new_modified')
    op.drop_table('YT_Chapter')
    op.alter_column('YT_Video', 'v',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('YT_Video', 'v',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_table('YT_Chapter',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YT_Chapter_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('movie_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('start', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('modified', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='YT_Chapter_pkey')
    )
    op.create_table('YT_new_modified',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"YT_new_modified_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('obiekt', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('obiekt_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='YT_new_modified_pkey')
    )
    # ### end Alembic commands ###
