"""empty message

Revision ID: f966935b2413
Revises: a38c0c64bfa3
Create Date: 2024-02-14 14:49:54.982088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f966935b2413'
down_revision = 'a38c0c64bfa3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('YT_LoadMore',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('YT_PlaylistVideo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.String(length=36), nullable=False),
    sa.Column('playlist_uuid', sa.String(length=36), nullable=False),
    sa.Column('video_uuid', sa.String(length=36), nullable=False),
    sa.Column('modified', sa.DateTime(), nullable=True),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('LoadMore')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('LoadMore',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"LoadMore_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user_uuid', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('data', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='LoadMore_pkey')
    )
    op.drop_table('YT_PlaylistVideo')
    op.drop_table('YT_LoadMore')
    # ### end Alembic commands ###
